site_name: Portray

theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.suggest
  language: en
  palette:
    - scheme: default
      primary: green
      accent: lightgreen

markdown_extensions:
  - admonition
  - codehilite
  - extra
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  - portray
